# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-23 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatars/'),
        ),
    ]
